import { FiCpu, FiZap } from "react-icons/fi";

/** Shows whether a result came from Gemini or the built-in Smart Engine. */
function SourceBadge({ meta, className = "" }) {
  if (!meta?.source) return null;
  const local = meta.source === "local";
  const cached = meta.source === "cache";
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-medium border ${
        local ? "border-cyan-400/30 bg-cyan-400/10 text-cyan-300" : "border-violet-400/30 bg-violet-400/10 text-violet-300"
      } ${className}`}
      title={local ? "Generated by PrepAI's built-in Smart Engine (works even when Gemini is busy)" : `Generated by Gemini${meta.model ? ` (${meta.model})` : ""}`}
    >
      {local ? <FiCpu size={11} /> : <FiZap size={11} />}
      {local ? "Smart Engine" : cached ? "Gemini (cached)" : "Gemini AI"}
    </span>
  );
}

export default SourceBadge;
