/** Text-based PDF reports (selectable text, small files). jsPDF is loaded on demand. */

async function buildPdf({ title, subtitle, sections, filename }) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  const maxW = W - M * 2;
  let y = M;

  const ensure = (h) => {
    if (y + h > H - M) {
      doc.addPage();
      y = M;
    }
  };
  const text = (str, { size = 10.5, bold = false, color = [40, 44, 60], indent = 0, gap = 4 } = {}) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(String(str), maxW - indent);
    for (const line of lines) {
      ensure(size + 4);
      doc.text(line, M + indent, y);
      y += size + 4;
    }
    y += gap;
  };

  // Header band
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, W, 78, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(title, M, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(subtitle || "", M, 60);
  y = 108;

  for (const s of sections) {
    ensure(40);
    text(s.heading, { size: 13, bold: true, color: [79, 70, 229], gap: 2 });
    doc.setDrawColor(220, 224, 240);
    doc.line(M, y - 2, W - M, y - 2);
    y += 6;
    for (const item of s.items || []) {
      if (typeof item === "string") text(`•  ${item}`, { indent: 6, gap: 2 });
      else if (item.kv) text(`${item.kv[0]}:  ${item.kv[1]}`, { indent: 6, gap: 1 });
      else if (item.para) text(item.para, { gap: 6 });
    }
    y += 8;
  }

  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8.5);
    doc.setTextColor(140, 146, 170);
    doc.text(`Generated by PrepAI · ${new Date().toLocaleDateString()}`, M, H - 24);
    doc.text(`Page ${i} / ${pages}`, W - M - 50, H - 24);
  }
  doc.save(filename);
}

export function downloadAnalysisPDF(analysis, name = "Resume") {
  const a = analysis || {};
  const s = a.stats || {};
  return buildPdf({
    title: "Resume Analysis Report",
    subtitle: `${name} · ATS score ${a.atsScore ?? "–"}/100 · ${a.experienceLevel || ""}`,
    filename: `PrepAI-resume-report.pdf`,
    sections: [
      { heading: "Summary", items: [{ para: a.summary || "—" }] },
      {
        heading: "Score breakdown (each out of 20)",
        items: Object.entries(a.scoreBreakdown || {}).map(([k, v]) => ({ kv: [k.charAt(0).toUpperCase() + k.slice(1), `${v}/20`] })),
      },
      {
        heading: "Key stats",
        items: [
          { kv: ["Words", s.wordCount ?? "–"] },
          { kv: ["Technical skills found", s.skillCount ?? "–"] },
          { kv: ["Quantified bullets", `${s.quantified ?? 0} (${s.quantifiedPct ?? 0}%)`] },
          { kv: ["Strong action verbs", `${s.actionVerbPct ?? 0}% of bullets`] },
          { kv: ["Estimated experience", `${s.yearsExperience ?? 0} years`] },
        ],
      },
      { heading: "Strengths", items: a.strengths || [] },
      { heading: "Weaknesses", items: a.weaknesses || [] },
      { heading: "Suggestions", items: a.suggestions || [] },
      {
        heading: "ATS checks",
        items: (a.checks || []).map((c) => `[${String(c.status).toUpperCase()}] ${c.label}: ${c.detail}${c.tip ? ` — Fix: ${c.tip}` : ""}`),
      },
      { heading: "Technical skills", items: [{ para: (a.technicalSkills || []).join(", ") || "—" }] },
      {
        heading: "Best-fit roles",
        items: (a.roleFit || []).map((r) => `${r.role} — ${r.fit}% fit${r.missing?.length ? ` (add: ${r.missing.slice(0, 4).join(", ")})` : ""}`),
      },
    ],
  });
}

export function downloadMatchPDF(result, resumeName = "Resume") {
  const r = result || {};
  return buildPdf({
    title: "Job Match Report",
    subtitle: `${r.jobTitle || "Target role"}${r.company ? " @ " + r.company : ""} · ${r.atsScore ?? "–"}% · ${r.verdict || ""} · ${resumeName}`,
    filename: "PrepAI-job-match-report.pdf",
    sections: [
      { heading: "Fit summary", items: [{ para: r.insights?.fitSummary || r.verdict || "—" }] },
      { heading: "Matched skills", items: [{ para: (r.matchedSkills || []).join(", ") || "None" }] },
      {
        heading: "Missing skills",
        items: (r.missingSkillsDetail || []).map((m) => `${m.skill} (${m.importance})`),
      },
      { heading: "Missing keywords", items: [{ para: (r.keywordsMissing || []).map((k) => k.term).join(", ") || "None" }] },
      { heading: "Recommendations", items: r.recommendations || [] },
      {
        heading: "Suggested resume bullets (replace placeholders with real numbers)",
        items: (r.insights?.tailoredBullets || []).map((b) => `${b.forSkill ? b.forSkill + ": " : ""}${b.bullet}`),
      },
      {
        heading: "Learning roadmap",
        items: (r.roadmap?.items || []).map((i) => `${i.skill} — ~${i.estimatedHours}h · ${i.priority} priority · project: ${i.projectIdea}`),
      },
    ],
  });
}

export function downloadTextFile(text, filename) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
